// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDshWC2SD8qbiw2IOQqMsXG3RrQbrSxmc',
    appId: '1:402708018802:web:bc7aa305c73b7084def4eb',
    messagingSenderId: '402708018802',
    projectId: 'bladmin-26b27',
    authDomain: 'bladmin-26b27.firebaseapp.com',
    storageBucket: 'bladmin-26b27.firebasestorage.app',
    measurementId: 'G-GRWGGR6ERP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3wj6QqLRzsu8cKaBqBc5bDsCKJS70_jg',
    appId: '1:402708018802:android:ed60e72a032008dadef4eb',
    messagingSenderId: '402708018802',
    projectId: 'bladmin-26b27',
    storageBucket: 'bladmin-26b27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvWqBjKMU04DJYvYY0UAkiK4ZqJfRes2c',
    appId: '1:402708018802:ios:6bbec43b672fb040def4eb',
    messagingSenderId: '402708018802',
    projectId: 'bladmin-26b27',
    storageBucket: 'bladmin-26b27.firebasestorage.app',
    iosBundleId: 'com.bla.realestate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvWqBjKMU04DJYvYY0UAkiK4ZqJfRes2c',
    appId: '1:402708018802:ios:6bbec43b672fb040def4eb',
    messagingSenderId: '402708018802',
    projectId: 'bladmin-26b27',
    storageBucket: 'bladmin-26b27.firebasestorage.app',
    iosBundleId: 'com.bla.realestate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDshWC2SD8qbiw2IOQqMsXG3RrQbrSxmc',
    appId: '1:402708018802:web:d1a4556604b09e6ddef4eb',
    messagingSenderId: '402708018802',
    projectId: 'bladmin-26b27',
    authDomain: 'bladmin-26b27.firebaseapp.com',
    storageBucket: 'bladmin-26b27.firebasestorage.app',
    measurementId: 'G-GNQ7FFP95Q',
  );

}